### ISSUE TITLE
problem while executing

### ISSUE THREAD

**Issue by Sunam-Rijal** [pieterbork/blueborne#1]
I got a problem while executing the script. 
Error: 
Traceback (most recent call last):
  File "cve20170785.py", line 2, in <module>
    import bluetooth
  File "/usr/local/lib/python2.7/dist-packages/bluetooth/__init__.py", line 282, in <module>
    """
AttributeError: attribute '__doc__' of 'instancemethod' objects is not writable

how can i solve this issue???

**Comment by itzpa1** [comment]
Same problem

**Comment by eliasdn** [comment]
i had the same issue and fixed it by replacing  "/usr/local/lib/python2.7/dist-packages/bluetooth/init.py" by  [this](https://github.com/karulis/pybluez/blob/master/bluetooth/__init__.py) init.py
